# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='star_average',
            field=models.FloatField(default=0.0),
        ),
    ]
