# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='making_country',
        ),
        migrations.AddField(
            model_name='movie',
            name='making_country',
            field=models.ManyToManyField(to='movie.MakingCountry'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.CharField(max_length=30),
        ),
    ]
