# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
