# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Release_date',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
