# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment_users',
            field=models.ManyToManyField(related_name='movie_set_comment_users', through='movie.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
