# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0002_auto_20161201_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousline',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='famouslines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
