# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_comment_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='makingcountry',
            old_name='making_country',
            new_name='content',
        ),
    ]
