# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_famousline_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famousline',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FamousLineAuthor', to=settings.AUTH_USER_MODEL),
        ),
    ]
