# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20161202_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxofficemovie',
            name='img_url',
        ),
        migrations.AddField(
            model_name='boxofficemovie',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxofficemovie',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boxofficemovie',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
