# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20161204_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='main_trailer',
            field=models.TextField(default='blanck'),
            preserve_default=False,
        ),
    ]
