# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161209_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='nickname', max_length=10),
            preserve_default=False,
        ),
    ]
