# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161128_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z0-9]){5,10}$')]),
        ),
    ]
