# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20161128_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z0-9]){4,10}$')]),
        ),
    ]
